# docker-compose.yml
services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  api1:
    build: .
    ports:
      - 8001:8000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  api2:
    build: .
    ports:
      - 8002:8000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  api3:
    build: .
    ports:
      - 8003:8000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis_data:
